module Pvectl
  module Services
    class Cloudinit
      VALID_DUMP_TYPES: Array[String]

      def initialize: (vm_repository: untyped, resource_resolver: untyped) -> void

      def regenerate: (Integer | String vmid, ?node: String?) -> Hash[Symbol, untyped]

      def pending: (Integer | String vmid, ?node: String?) -> Array[Hash[Symbol, untyped]]

      def dump: (Integer | String vmid, String type, ?node: String?) -> String

      private

      def resolve_node!: (Integer | String vmid) -> String
    end
  end
end
