module Pvectl
  module Presenters
    class Base
      def columns: () -> Array[String]

      def wide_columns: () -> Array[String]

      def extra_columns: () -> Array[String]

      def to_row: (untyped model, **untyped context) -> Array[String?]

      def to_wide_row: (untyped model, **untyped context) -> Array[String?]

      def extra_values: (untyped model, **untyped context) -> Array[String?]

      def to_hash: (untyped model) -> Hash[String, untyped]

      def to_description: (untyped model) -> Hash[String, untyped]

      def uptime_human: () -> String

      def tags_array: () -> Array[String]

      def tags_display: () -> String

      def template_display: () -> String

      private

      def resource: () -> untyped

      def format_bytes: (Integer? bytes) -> String
    end
  end
end
