module Pvectl
  module Presenters
    class Capability < Base
      def columns: () -> Array[String]

      def extra_columns: () -> Array[String]

      def to_row: (untyped model, **untyped context) -> Array[String]

      def extra_values: (untyped model, **untyped context) -> Array[String]

      def to_hash: (untyped model) -> Hash[String, untyped]

      private

      def details: (untyped model) -> String
    end
  end
end
