module Pvectl
  module Presenters
    class Container < Base
      def columns: () -> Array[String]

      def extra_columns: () -> Array[String]

      def to_row: (untyped model, **untyped context) -> Array[String?]

      def extra_values: (untyped model, **untyped context) -> Array[String?]

      def to_hash: (untyped model) -> Hash[String, untyped]

      def to_description: (untyped model) -> Hash[String, untyped]

      def display_name: () -> String

      def cpu_percent: () -> String

      def memory_used_gib: () -> Float?

      def memory_total_gib: () -> Float?

      def memory_display: () -> String

      def swap_used_mib: () -> Float?

      def swap_total_mib: () -> Float?

      def swap_display: () -> String

      def disk_used_gib: () -> Float?

      def disk_total_gib: () -> Float?

      def disk_display: () -> String

      def pool_display: () -> String

      def netin_display: () -> String

      def netout_display: () -> String

      private

      attr_reader container: untyped
      alias resource container

      @consumed_keys: Set[Symbol]

      def format_system: (?Hash[Symbol, untyped] config) -> Hash[String, String]

      def format_cpu: (?Hash[Symbol, untyped] config) -> Hash[String, untyped]

      def format_memory: () -> Hash[String, String]

      def format_swap: () -> Hash[String, String]

      def format_rootfs: (?Hash[Symbol, untyped] config) -> Hash[String, String]

      def format_network_interfaces: (?Hash[Symbol, untyped] config) -> (Array[Hash[String, String]] | String)

      def format_features: (?Hash[Symbol, untyped] config) -> String

      def format_mountpoints: (Hash[Symbol, untyped] config) -> (Array[Hash[String, String]] | String)

      def format_dns: (Hash[Symbol, untyped] config) -> (Hash[String, String] | String)

      def format_console: (Hash[Symbol, untyped] config) -> (Hash[String, untyped] | String)

      def format_snapshots: (Array[Hash[Symbol, untyped]]? snapshots) -> (Array[Hash[String, String?]] | String)

      def format_runtime: () -> (Hash[String, untyped] | String)

      def consume_misc_keys: (Hash[Symbol, untyped] config) -> void

      def consume: (*Symbol keys) -> void

      def consume_matching: (Hash[Symbol, untyped] config, Regexp pattern) -> void

      def format_remaining: (Hash[Symbol, untyped] config) -> (Array[Hash[String, String]] | String)
    end
  end
end
