module Pvectl
  module Presenters
    class Disk < Base
      def columns: () -> Array[String]

      def extra_columns: () -> Array[String]

      def to_row: (untyped model, **untyped context) -> Array[String]

      def extra_values: (untyped model, **untyped context) -> Array[String]

      def to_hash: (untyped model) -> Hash[String, untyped]

      def to_description: (untyped model) -> Hash[String, untyped]

      private

      attr_reader disk: untyped

      def format_size: () -> String

      def format_boolean: (Integer? value) -> String

      def device_info_section: () -> Hash[String, String]

      def smart_attributes_section: () -> Array[Hash[String, String]]

      def format_ata_attributes: () -> Array[Hash[String, String]]
    end
  end
end
