module Pvectl
  module Presenters
    class TopVm < Vm
      include TopPresenter

      def columns: () -> Array[String]

      def extra_columns: () -> Array[String]

      def to_row: (untyped model, **untyped context) -> Array[String]

      def extra_values: (untyped model, **untyped context) -> Array[String]

      def to_hash: (untyped model) -> Hash[String, untyped]
    end
  end
end
