module Pvectl
  module Commands
    module Resize
      class ResizeVolumeCt
        include ResizeVolumeCommand

        private

        def resource_label: () -> String
        def resource_id_label: () -> String
        def build_resize_service: (Connection connection) -> Services::ResizeVolume
        def build_presenter: () -> Presenters::ContainerOperationResult
      end
    end
  end
end
