module Pvectl
  module Commands
    module Get
      module ResourceHandler
        def list: (?node: String?, ?name: String?, **untyped) -> Array[untyped]

        def presenter: () -> Presenters::Base
      end
    end
  end
end
