module Pvectl
  module Commands
    class EditVm
      include EditResourceCommand

      def self.register: (untyped cli) -> void

      private

      def resource_label: () -> String

      def resource_id_label: () -> String

      def execute_params: (String resource_id) -> Hash[Symbol, Integer]

      def build_edit_service: (untyped connection) -> Services::EditVm
    end
  end
end
