module Pvectl
  module Commands
    class EditContainer
      include EditResourceCommand

      private

      def resource_label: () -> String

      def resource_id_label: () -> String

      def execute_params: (Integer resource_id) -> Hash[Symbol, untyped]

      def build_edit_service: (untyped connection) -> Services::EditContainer
    end
  end
end
