module Pvectl
  module Commands
    class EditNode
      include EditResourceCommand

      private

      def resource_label: () -> String

      def resource_id_label: () -> String

      def execute_params: (String resource_id) -> Hash[Symbol, String]

      def build_edit_service: (untyped connection) -> Services::EditNode
    end
  end
end
