module Pvectl
  module Commands
    class FeatureVm
      include FeatureCommand

      RESOURCE_TYPE: Symbol
      SUPPORTED_RESOURCES: Array[String]

      def self.register: (untyped cli) -> void
    end
  end
end
