module Pvectl
  module Commands
    class MoveDiskVm
      include MoveDiskCommand

      RESOURCE_TYPE: Symbol

      SUPPORTED_RESOURCES: Array[String]

      def self.register: (untyped cli) -> void
    end
  end
end
