module Pvectl
  module Commands
    class TemplateVm
      include TemplateCommand

      RESOURCE_TYPE: Symbol
      SUPPORTED_RESOURCES: Array[String]

      def self.register: (untyped cli) -> void
    end
  end
end
